server:
  port: 8088
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://tlzrrbdijeptmt:f87ed9d0724cfef62facf1ae0a0c767509531b01c295b01f2903db529e9a9e75@ec2-3-212-75-25.compute-1.amazonaws.com:5432/d5k5k8qun6ma9h
    username: tlzrrbdijeptmt
    password: f87ed9d0724cfef62facf1ae0a0c767509531b01c295b01f2903db529e9a9e75
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true 
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado durante o Santander Dev Week (backend)